---
title: "Analysis of false-belief task performance"
author: "Sean Trott"
date: "10/3/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    # code_folding: hide
  pdf_document: default
  word_document:
    toc: yes
---

```{r include=FALSE}
library(tidyverse)
library(lme4)
library(ggridges)
library(broom.mixed)
library(lmerTest)
library(corrplot)
```



# Load data

Here, we load the surprisal data for the simple false-belief task, calculated from each of the models. 

## BERT 

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/NLMs/nlm-fb/src/analysis")

df_fb_bl = read_csv("../../data/processed/fb_bert-large_surprisals.csv")
nrow(df_fb_bl)
table(df_fb_bl$condition)
table(df_fb_bl$item)
table(df_fb_bl$a)

df_fb_bl = df_fb_bl %>%
  mutate(mentions_ratio = mentions_start / mentions_end) 


```

## GPT-3

```{r}
df_fb_gpt3 = read_csv("../../data/processed/fb_gpt3_surprisals.csv")
nrow(df_fb_gpt3)
table(df_fb_gpt3$condition)
table(df_fb_gpt3$item)

df_fb_gpt3 = df_fb_gpt3 %>%
  mutate(mentions_ratio = mentions_start / mentions_end) 
```


# Visualization

## BERT

```{r}

## Density version
df_fb_bl %>%
  ggplot(aes(x = log_odds,
             y = first_mention,
             fill = condition)) +
  geom_density_ridges2(aes(height = ..density..), 
                       color=gray(0.25), 
                       alpha = 0.5, 
                       scale=0.85, 
                       size=.9, 
                       stat="density") +
  labs(x = "Log-odds (start vs. end)",
       y = "First mention (start vs. end)") +
  geom_vline(xintercept = 0, linetype = "dotted") +
  theme_bw() +
  facet_wrap(~knowledge_cue + mentions_ratio,
             nrow = 2)


## Strip chart version
df_fb_bl %>%
  ggplot(aes(x = condition,
             y = log_odds,
             color = condition)) +
  geom_jitter(alpha = .1) +
  stat_summary (fun = function(x){mean(x)},
                fun.min = function(x){mean(x) - 2*sd(x)/sqrt(length(x))},
                fun.max = function(x){mean(x) + 2*sd(x)/sqrt(length(x))},
                geom= 'pointrange', 
                position=position_dodge(width=0.95)) +
  labs(x = "Condition",
       y = "Log-odds (start vs. end)") +
  geom_hline(yintercept = 0, linetype = "dotted") +
  theme_bw() +
  facet_wrap(~knowledge_cue + mentions_ratio,
             nrow = 2)

## Strip chart version
df_fb_bl %>%
  ggplot(aes(x = first_mention,
             y = log_odds,
             color = first_mention)) +
  geom_jitter(alpha = .1) +
  stat_summary (fun = function(x){mean(x)},
                fun.min = function(x){mean(x) - 2*sd(x)/sqrt(length(x))},
                fun.max = function(x){mean(x) + 2*sd(x)/sqrt(length(x))},
                geom= 'pointrange', 
                position=position_dodge(width=0.95)) +
  labs(x = "Condition",
       y = "Log-odds (start vs. end)") +
  geom_hline(yintercept = 0, linetype = "dotted") +
  theme_bw()

```

## GPT-3


```{r}

## Density version
df_fb_gpt3 %>%
  ggplot(aes(x = log_odds,
             y = first_mention,
             fill = condition)) +
  geom_density_ridges2(aes(height = ..density..), 
                       color=gray(0.25), 
                       alpha = 0.5, 
                       scale=0.85, 
                       size=.9, 
                       stat="density") +
  labs(x = "Log-odds (start vs. end)",
       y = "First mention (start vs. end)") +
  geom_vline(xintercept = 0, linetype = "dotted") +
  theme_bw() +
  facet_wrap(~knowledge_cue + mentions_ratio,
             nrow = 2)

## Strip chart version
df_fb_gpt3 %>%
  ggplot(aes(x = condition,
             y = log_odds,
             color = condition)) +
  geom_jitter(alpha = .05) +
  stat_summary (fun = function(x){mean(x)},
                fun.min = function(x){mean(x) - 2*sd(x)/sqrt(length(x))},
                fun.max = function(x){mean(x) + 2*sd(x)/sqrt(length(x))},
                geom= 'pointrange', 
                position=position_dodge(width=0.95)) +
  labs(x = "Condition",
       y = "Log-odds (start vs. end)") +
  geom_hline(yintercept = 0, linetype = "dotted") +
  theme_bw() +
  facet_wrap(~knowledge_cue + mentions_ratio,
             nrow = 2)

```

## Comparison of LMs

```{r}
df_fb_bl$gpt_log_odds = df_fb_gpt3$log_odds

df_fb_bl %>%
  ggplot(aes(x = log_odds,
             y = gpt_log_odds,
             color = condition,
             shape = first_mention,
             size = mentions_ratio)) +
  geom_point(alpha = .3) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_vline(xintercept = 0, linetype = "dotted") +
  labs(x = "BERT log-odds",
       y = "GPT-3 log-odds") +
  # scale_x_continuous(limits = c(-5, 10)) +
  # scale_y_continuous(limits = c(-5, 10)) +
  theme_bw() +
  facet_wrap(~knowledge_cue)
```


# Analysis

## BERT

```{r}
model_full = lmer(data = df_fb_bl,
                  log_odds ~ condition * knowledge_cue + 
                    first_mention + mentions_ratio +
                    (1 + condition | a) +
                    (1 + condition | b) +
                    (1 + condition | item) +
                    (1 | start) +
                    (1 | end),
                  control=lmerControl(optimizer="bobyqa"),
                  REML = FALSE)

model_just_fe = lmer(data = df_fb_bl,
                  log_odds ~ condition + knowledge_cue +
                    first_mention + mentions_ratio + 
                    (1 + condition  | a) +
                    (1 + condition  | b) +
                    (1 + condition  | item) +
                    (1| start) +
                    (1  | end),
                  control=lmerControl(optimizer="bobyqa"),
                  REML = FALSE)


model_no_condition = lmer(data = df_fb_bl,
                  log_odds ~ knowledge_cue +
                    first_mention + mentions_ratio + 
                    (1 + condition  | a) +
                    (1 + condition  | b) +
                    (1 + condition  | item) +
                    (1| start) +
                    (1  | end),
                  control=lmerControl(optimizer="bobyqa"),
                  REML = FALSE)

summary(model_full)
anova(model_full, model_just_fe)
anova(model_just_fe, model_no_condition)


df_tidy_results = broom.mixed::tidy(model_full)

df_tidy_results %>%
  filter(effect == "fixed") %>%
  ggplot(aes(x = term,
             y = estimate)) +
  geom_point() +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_errorbar(aes(ymin = estimate - 2*std.error, 
                    ymax = estimate + 2*std.error), 
                width=.2,
                position=position_dodge(.9)) +
  theme_minimal()
```


## GPT-3

```{r}

model_full = lmer(data = df_fb_gpt3,
                  log_odds ~ condition * knowledge_cue + 
                    first_mention + mentions_ratio +
                    (1 | a) +
                    (1 | b) +
                    (1 | item) +
                    (1 | start) +
                    (1 | end),
                  control=lmerControl(optimizer="bobyqa"),
                  REML = FALSE)

model_just_fe = lmer(data = df_fb_gpt3,
                  log_odds ~ condition + knowledge_cue +
                    first_mention + mentions_ratio + 
                    (1  | a) +
                    (1  | b) +
                    (1  | item) +
                    (1| start) +
                    (1  | end),
                  control=lmerControl(optimizer="bobyqa"),
                  REML = FALSE)


model_no_condition = lmer(data = df_fb_gpt3,
                  log_odds ~ knowledge_cue +
                    first_mention + mentions_ratio + 
                    (1  | a) +
                    (1  | b) +
                    (1  | item) +
                    (1| start) +
                    (1  | end),
                  control=lmerControl(optimizer="bobyqa"),
                  REML = FALSE)

summary(model_full)
anova(model_full, model_just_fe)
anova(model_just_fe, model_no_condition)


df_tidy_results = broom.mixed::tidy(model_full)

df_tidy_results %>%
  filter(effect == "fixed") %>%
  ggplot(aes(x = term,
             y = estimate)) +
  geom_point() +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_errorbar(aes(ymin = estimate - 2*std.error, 
                    ymax = estimate + 2*std.error), 
                width=.2,
                position=position_dodge(.9)) +
  theme_minimal()
```

